services:
  - type: web
    name: maxwintv-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8355178835:AAH460fjfgwYbGBM5FEtzzhtUhTk6EM6dBA"
